# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5f5996dc45ea7687641c933309dde1f6a514d62dc2c99723c99b147f6ae0db9bbe9dd1902ee92a9b2d5f80456bdb3710d208b7b31b7c7b77091e6ef892cc1a4

test:
  secret_key_base: a7a52565a732c0108955537be0081c05f4920d2a93bec639f1e16e59cb4d4faaf4e9332de6f52fb15995306500a6f7dfb4b1df37b61e10e3da74cd18a8134cd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
